### ISSUE TITLE
Replace 'z' with 'zoxide'

### ISSUE THREAD

**Issue by ss-o** [z-shell/zw#540]
https://github.com/z-shell/zw/blob/8f2372c61560a8272fcd87cac499d67e458c2e68/docs/gallery/collection/01_4_snippets.md?plain=1#L40

Hi @xfzv,

Could you propose installation for `zoxide` instead of `z`? 

Thanks,

**Comment by xfzv** [comment]
https://github.com/ajeetdsouza/zoxide/issues/175#issuecomment-841470951:

This used to work just fine with original `zinit`. I haven't tried it with `zi` but I think it should work too.

---

Now, as far as I'm concerned, I install `zoxide` via my distro package manager and simply load it with:

```zsh
eval "$(zoxide init --no-cmd zsh)"
```

I also explicitely assign `z` and `zi` to `__zoxide_z` and `__zoxide_zi` respectively in my `aliases.zsh` file:

```zsh
[[ -v "commands[zoxide]" ]] && alias z="__zoxide_z" && alias zi="__zoxide_zi"
```

so that it doesn't conflict with `zi`.

**Comment by ss-o** [comment]
Seems that `zi/zoxide` causing problems everywhere: https://github.com/r-darwish/topgrade/issues/935

It seems reasonable to put a notice about name collision and propose to the user how to set up an alias to choose which name to change?

Thanks for the reply,

**Comment by ss-o** [comment]
> [ajeetdsouza/zoxide#175 (comment)](https://github.com/ajeetdsouza/zoxide/issues/175#issuecomment-841470951):
> 
> This used to work just fine with original `zinit`. I haven't tried it with `zi` but I think it should work too.
> 
> Now, as far as I'm concerned, I install `zoxide` via my distro package manager and simply load it with:
> 
> ```shell
> eval "$(zoxide init --no-cmd zsh)"
> ```
> 
> I also explicitely assign `z` and `zi` to `__zoxide_z` and `__zoxide_zi` respectively in my `aliases.zsh` file:
> 
> ```shell
> [[ -v "commands[zoxide]" ]] && alias z="__zoxide_z" && alias zi="__zoxide_zi"
> ```
> 
> so that it doesn't conflict with `zi`.

What do you type to invoke `zi` and `zoxide` for each respectively?

**Comment by xfzv** [comment]
> What do you type to invoke `zi` and `zoxide` for each respectively?

- `zi`: I'm still using `\zi`, I haven't migrated to a custom [`❮▼❯` alias](https://github.com/z-shell/zi/blob/main/zi.zsh#L2680) yet.
- `zoxide`: `z` and `zi`.
